SELECT HIV.YEAR, HIV.COUNTY, DIAGNOSES, POPULATION, USERS
	FROM HIV INNER JOIN POP
	ON HIV.COUNTY = POP.COUNTY AND HIV.YEAR = POP.YEAR
	INNER JOIN PrEP
	ON HIV.COUNTY = PrEP.COUNTY AND HIV.YEAR = PrEP.YEAR
;
	
--multiply by 1.0 to show decimal. FLOAT
SELECT POP.YEAR, SUM(POPULATION) as population,
	SUM(DIAGNOSES) as diagnoses,
	100000.0*SUM(DIAGNOSES)/sum(POPULATION) as incidenceRate,
	100000.0*sum(USERS)/sum(population) as prepRate,
	1.0*SUM(USERS)/SUM(DIAGNOSES) AS pnr
	FROM POP LEFT JOIN HIV
	ON HIV.COUNTY = POP.COUNTY AND HIV.YEAR = POP.YEAR
	LEFT JOIN PrEP
	ON POP.COUNTY = PrEP.COUNTY AND POP.YEAR = PrEP.YEAR
	GROUP BY POP.YEAR
;

--*100k